repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: mixed-line-ending
        -   id: trailing-whitespace
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
        -   id: fmt
        -   id: cargo-check
