[package]
name = "rust_dl_lib"
version = "0.1.0"
authors = ["Anton Paramoshin <antonparamoshin@.gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
rand = "0.7.3"
rand_distr = "0.2.2"